In [3]:
import pandas as pd

In [4]:
data1 = {
    "Name" : ["ABC","DEF","GHI","JKL"],
    "Marks" : [90,67,85,90]
}
df1 = pd.DataFrame(data1)

In [5]:
print(df1)

  Name  Marks
0  ABC     90
1  DEF     67
2  GHI     85
3  JKL     90

In [12]:
print(df1["Marks"]>70)

0     True
1    False
2     True
3     True
Name: Marks, dtype: bool

In [11]:
print(df1[df1["Marks"]>70])

  Name  Marks
0  ABC     90
2  GHI     85
3  JKL     90

In [14]:
# sort values function = sort_values()

In [20]:
df2 = pd.DataFrame(data1)
df2.sort_values("Marks") # ascending = True

  Name  Marks
1  DEF     67
2  GHI     85
0  ABC     90
3  JKL     90

In [19]:
df2 = pd.DataFrame(data1)
df2.sort_values("Marks", ascending = False) # descending -> ascending = False

  Name  Marks
0  ABC     90
3  JKL     90
2  GHI     85
1  DEF     67

In [39]:
data2 = {
    "Name" : ["ABC","DEF","GHI","JKL"],
    "Marks" : [90,67,85,90],
    "Age" : [22,23,21,23]
}
df2 = pd.DataFrame(data2)
print(df2[["Name","Marks"]])

  Name  Marks
0  ABC     90
1  DEF     67
2  GHI     85
3  JKL     90

In [40]:
# Handling Missing values

In [55]:
# Function is used
# df.isnull() 
# df4.dropna()
# df3.fillna(To_fill, inplace = True)

In [53]:
import numpy as np
data3 ={
    "Name" : ["ABC","DEF","GHI","JKL"],
    "Marks" : [90,67,np.nan,90]   
}
df3 = pd.DataFrame(data3)
print(df3)

  Name  Marks
0  ABC   90.0
1  DEF   67.0
2  GHI    NaN
3  JKL   90.0

In [54]:
# Identifying missing values
df3.isnull()

    Name  Marks
0  False  False
1  False  False
2  False   True
3  False  False

In [51]:
data4 ={
    "Name" : ["ABC","DEF","GHI","JKL"],
    "Marks" : [90,67,np.nan,90]   
}
df4 = pd.DataFrame(data4)
print(df4)

  Name  Marks
0  ABC   90.0
1  DEF   67.0
2  GHI    NaN
3  JKL   90.0

In [52]:
# Removing missng value
df4.dropna()

  Name  Marks
0  ABC   90.0
1  DEF   67.0
3  JKL   90.0

In [56]:
# Filling missing values
df3.fillna(0, inplace = True)

  Name  Marks
0  ABC   90.0
1  DEF   67.0
2  GHI    0.0
3  JKL   90.0

In [58]:
# Replacing by mean
data5 ={
    "Name" : ["ABC","DEF","GHI","JKL"],
    "Marks" : [90,67,np.nan,90]   
}
df5 = pd.DataFrame(data5)
df5.fillna(df5["Marks"].mean())

  Name      Marks
0  ABC  90.000000
1  DEF  67.000000
2  GHI  82.333333
3  JKL  90.000000

In [59]:
# Replacing by unknown
data6 ={
    "Name" : ["ABC","DEF","GHI","JKL"],
    "Marks" : [90,67,np.nan,90]   
}
df6 = pd.DataFrame(data6)
df6.fillna("Unknown")

  Name    Marks
0  ABC     90.0
1  DEF     67.0
2  GHI  Unknown
3  JKL     90.0

In [60]:
# Group by operation

In [68]:
emp = {
    "dept" : ["HR","IF","HR","IF"],
    "salary" : [10000,20000,15000,23000]
}
empDF = pd.DataFrame(emp)

In [70]:
print(empDF)

  dept  salary
0   HR   10000
1   IF   20000
2   HR   15000
3   IF   23000

In [69]:
empDF.groupby("dept")["salary"].mean()

dept
HR    12500.0
IF    21500.0
Name: salary, dtype: float64